### ISSUE TITLE
WRITE /.

### ISSUE THREAD

**Issue by larshp** [abaplint/transpiler#301]
bug, 

![image](https://user-images.githubusercontent.com/5888506/105343373-d2f56980-5be1-11eb-9c93-5091987ac4f6.png)

**Comment by arcanist123** [comment]
I don't think that this is something that is easy to implement. The problem here is the same why SAP cannot make the console realtime - result of this statement depends on the **next** statements to come
For example, this statement
``` abap
  WRITE /.
```
should produce nothing(based on the current implementation from SAP). And this statement 
``` abap
  WRITE /.
  WRITE 'TEST'.
```
should produce /nTEST
the question is - should this project reimplement the sap behavior (which is, imao, stupid and nonsensical ) - or should the implementation be a more logical translation of '/' into '/n' all the time regardless of preceding or following values in console
This decision has to be done by the maintainers of the project.
